### ISSUE TITLE
Not working for me anymore. 

### ISSUE THREAD

**Issue by Real-Rodville** [Meidor/keywordblocker#18]
It isn't working for me anymore. I have several keywords in and all of a sudden they all popped back up on my YouTube page.

**Comment by Meidor** [comment]
Do you know if you have the new layout of YouTube?
I'm currently working on a new version that fixes problems of the extension with the new layout.

**Comment by Real-Rodville** [comment]
I do have the new layout. I was using a different content blocker and when they moved to the new layout that one stopped working. There was the option to use the old layout and I did but they took that option away from me and I moved to your blocker. It worked with the new layout for about a month and then stopped.

**Comment by Meidor** [comment]
I'm trying to fix this problem as we speak so I hope to fix it soon!

**Comment by Real-Rodville** [comment]
OK thank you.

**Comment by Meidor** [comment]
I've pushed the new version that fixes the problems with the new layout to github. Will upload the update to the chrome extensionstore now. I'd love to hear if everything is working after this update on your end!

**Comment by Meidor** [comment]
@Real-Rodville are there any features from your old extension that you would love to see in my version?

**Comment by Real-Rodville** [comment]
The one I miss from the other one was the ability to right click and add videos or channels to the block list. 

Now if you want a wish list I would live to be able to filter out videos that are not in English. I am getting them in Arabic, Thai, Portuguese, and Tagalog. I am not even sure why but it would be nice to not have those.

**Comment by Meidor** [comment]
I've added rightclick on selection of text support and support for blocking of channels. Don't have the right click on channel/video to block the channel function yet as that is a bit harder than I thought. Filtering non english video's is not something I can easily support.

**Comment by Real-Rodville** [comment]
Thank you.
