### ISSUE TITLE
Feature: Hide videos, but don't block them if clicked

### ISSUE THREAD

**Issue by whatever1233** [Meidor/keywordblocker#33]
Hi

your extension basically is super useful.  However i would much more prefer to turn of the "stop" sign and simply let me watch a video if clicked, even if it contains blocked keywords.

I came to a point that almost all youtube videos are "unwatchable" with the extension.

Please let users turn of the "block" sign or have it turned off by default, and let people turn it on if they want.

Thank you so much.

**Comment by Meidor** [comment]
I'm working on a new, better version, of the extension as we speak and I will take your feedback into consideration. In the meantime if you find that the extension blocks a lot of videos that shouldn't be blocked turn of the match keywords in description. For some reason this function also triggers a block if the keyword appears in the comments under the video.
