### ISSUE TITLE
FEATURE:  Google Admin Panel Integration for deployment of JSON configs to manged devices.

### ISSUE THREAD

**Issue by kaned-mchs** [Meidor/keywordblocker#34]
I see the ability to export the json file.

Can you add the ability to have the config file distributed through the google administrative panel?  This would allow administrators to build a config and deploy it to their computers.

At this point, I do not see this ability within the admin panel for this specific extension.

**Comment by kaned-mchs** [comment]
yes, this is available within the admin panel.

As an admin I can tell you where that would be located... but I don't quite have the expertise to do write any code, let me see what i can find.

I can tell you that our barracuda Chromebook extension does this.

App ID:  mlbgnlemejoeocmncpolejmdbimkoiol

I have seen a few others but don't have any installed at the moment other than this one.

Let me see what I can find out!

**Comment by kaned-mchs** [comment]
https://campus.barracuda.com/product/websecuritygateway/doc/49744111/how-to-get-and-configure-the-barracuda-chromebook-security-extension/

About halfway down the page has a screenshot of what us admins see.

FYI

**Comment by Meidor** [comment]
Thanks, I will try looking in to this tomorrow!
