### ISSUE TITLE
Keyword Blocker does not seem to work at all

### ISSUE THREAD

**Issue by GenPDP7** [Meidor/keywordblocker#43]
I cannot get this extension to block anything at all on the latest version of Chrome.
Version 77.0.3865.90 (Official Build) (64-bit)

**Comment by Meidor** [comment]
I will check it out tomorrow!

**Comment by Meidor** [comment]
I've found and fixed the issue and will release a new version of the extension today that fixes the issue. Thank you for reporting it!

**Comment by Meidor** [comment]
New version is published
