### ISSUE TITLE
Block video by language used in description

### ISSUE THREAD

**Issue by beerbotboffin** [Meidor/keywordblocker#45]
I get a number of Japanese and Spanish language videos in my feed (I speak neither language) and 
have no interest in them. 

**Describe the solution you'd like**
What I would appreciate is the ability to block videos who are in certain languages, or possibly not in English.

**Comment by Meidor** [comment]
Sadly it is not easy to detect languages and I don't want to use an external service to do this because of privacy reasons. So I wont be implementing this feature.

Thank you for suggesting this enhancement though!
